data_path: "/data/moneydata.csv"
production_path: ""
mlflow_tracking_uri: "http://129.114.27.211:8000"
experiment_name: "m1-categorization-ray"
registered_model_name: "m1-ray-categorization"
quality_gate_macro_f1: 0.65

tfidf:
  ngram_min: 1
  ngram_max: 3
  max_features: 1000

model:
  n_estimators: 200
  max_depth: 6
  learning_rate: 0.1

split_date: "2021-01-01"
feedback_weight: 10   # repeat each feedback row N times to amplify user corrections
checkpoint_dir: "s3://proj16-mlflow-artifacts/ray-checkpoints"

s3:
  endpoint_url: "https://chi.tacc.chameleoncloud.org:7480"
