global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: "neural-budget"
    env: "local-dev"

scrape_configs:
  # m1 server runs as nohup process on host port 8001
  - job_name: "m1-serving"
    static_configs:
      - targets: ["host.docker.internal:8001"]
    metrics_path: /metrics
    scrape_interval: 15s

  # m2 server runs as nohup process on host port 8003
  - job_name: "m2-serving"
    static_configs:
      - targets: ["host.docker.internal:8003"]
    metrics_path: /metrics
    scrape_interval: 15s

  # m3 server runs as nohup process on host port 8002
  - job_name: "m3-serving"
    static_configs:
      - targets: ["host.docker.internal:8002"]
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
