data_path: "/data/synthetic_transactions.csv"
mlflow_tracking_uri: "http://129.114.25.172:8000"
experiment_name: "m3-forecasting"

prophet:
  changepoint_prior_scale: 0.05
  seasonality_prior_scale: 5.0
  seasonality_mode: "multiplicative"

min_months: 12
min_transactions: 50
split_months: 2
